// <auto-generated />
namespace TrabalhoBackEnd.Entidades
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TabelasSeguranca : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabelasSeguranca));
        
        string IMigrationMetadata.Id
        {
            get { return "201708311346551_TabelasSeguranca"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
